#!/bin/bash

_kill_procs() {
  kill -TERM $chromium
  wait $chromium
  kill -TERM $xvfb
}

# Setup a trap to catch SIGTERM and relay it to child processes
trap _kill_procs SIGTERM

#XVFB_WHD=${XVFB_WHD:-1280x720x16}
XVFB_WHD=${XVFB_WHD:-1280x800x16}

# Start Xvfb
Xvfb :99 -ac -screen 0 $XVFB_WHD -nolisten tcp &
xvfb=$!

export DISPLAY=:99

chromium --no-sandbox --remote-debugging-port=9222 --disable-dev-shm-usage --disable-infobars --disable-gpu --incognito --disable-application-cache --disable-extensions --disable-default-apps $@ &
chromium=$!

wait $chromium
wait $xvfb

